# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eekHIPklDGWRjt0xOyQp_oi68XDsSXTB
"""

import pandas as pd
import numpy as np
import openpyxl as xl

import os
import shutil

movements_df = pd.read_excel (r'/content/drive/My Drive/Colab Notebooks/EXPORTmb51.XLSX')

#transfers = list(df_gearME.ColA)
doc_nums_raw = movements_df["Material Document"].tolist()
doc_nums = []
for i in doc_nums_raw:
  if str(i)[:3] == "490" and (i in doc_nums) == False:
    doc_nums.append(np.int64(i))
temp = movements_df.loc[movements_df["Material Document"]  == doc_nums[0]]


for x in range(len(doc_nums)):
  current_df = movements_df.loc[movements_df["Material Document"]  == doc_nums[x]]
  for index, row in current_df.iterrows():
    print(row['Material'], row['Qty in Un. of Entry'])
    print(type(row['Material']),type(row['Qty in Un. of Entry']))
  print()

# copy file to new file, copy polish sheet to new sheet
#have to copy to new file because openpyxl won't support copying between workbooks

source_dir ='/content/drive/My Drive/Colab Notebooks/MASTER.xlsx'
destination_dir="/content/drive/My Drive/Colab Notebooks/TEST.xlsx"
shutil.copy(source_dir,destination_dir)
#coppy part
wb = xl.load_workbook(destination_dir) 
ws = wb.worksheets[0] 
source = wb.active
wb.copy_worksheet(ws)
wb.worksheets[5].title = 'TEST'
ws =  wb.worksheets[5]

for i in range(12, 65):
  if ws.cell(row = i, column = 1).value == "CM9048SASEBL25-EA":
    ws.cell(row = i, column = 3, value = i)
wb.save(str(destination_dir))

